<a href="https://colab.research.google.com/github/Esther11-code/Csharp-projects/blob/main/Assignment_Day_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercise 1: Student Exam Performance Analysis
Sarah, a high school teacher, wants to analyze the grades of her students to identify trends and patterns. She decides to use NumPy to perform various computations on the grade data. Sarah is a dedicated teacher who wants to ensure the success of her students. She collects data on their test scores and attendance to gain insights into their academic performance. Using NumPy, she performs various computations and analyses to understand how her students are progressing. So help you as a Data Scientist help Sarah in following activities.

Tasks:
Create Grade Data: Sarah has a list of 10 students and their test scores (out of 100). So create a 1D array containing these scores.

Analyze Test Scores: Sarah wants to analyze the test scores to understand how her students performed. So create a 2D array with 3 rows (representing three tests) and 10 columns (representing the students' scores).

Reshape the Data: Reshape the 2D array into a 3D array to perform deeper analysis.

Calculate Average Scores: Calculates the average score for each test to understand the overall performance of her students.

Generate Attendance Data: Sarah also wants to track student attendance. So generate a 1D array containing 10 randomly generated attendance percentages for each student.

In [9]:
import numpy as np

"""Grade Data"""
test_scores_1D = np.array([85, 90, 75, 60, 92, 78, 88, 70, 95, 83])

"""Analyze Test Scores"""
test_scores_2D = np.array([
    [85, 90, 75, 60, 92, 78, 88, 70, 95, 83],  # first test
    [78, 85, 80, 65, 90, 75, 85, 68, 92, 80],  # second test
    [82, 88, 72, 58, 94, 80, 90, 72, 96, 85]   # third test
])

"""reshape the data"""
test_scores_3D = test_scores_2D.reshape(3, 5, 2)

"""calculate average scores"""
average_scores = np.mean(test_scores_2D, axis=1)

"""attendance data"""
attendance_percentages = np.random.randint(50, 100, 10)

# Print the results
print("Grade Data (1D array):\n", test_scores_1D)
print("\nTest Scores (2D array):\n", test_scores_2D)
print("\nReshaped Test Scores (3D array):\n", test_scores_3D)
print("\nAverage Scores (1D array):\n", average_scores)
print("\nAttendance Data (1D array):\n", attendance_percentages)


Grade Data (1D array):
 [85 90 75 60 92 78 88 70 95 83]

Test Scores (2D array):
 [[85 90 75 60 92 78 88 70 95 83]
 [78 85 80 65 90 75 85 68 92 80]
 [82 88 72 58 94 80 90 72 96 85]]

Reshaped Test Scores (3D array):
 [[[85 90]
  [75 60]
  [92 78]
  [88 70]
  [95 83]]

 [[78 85]
  [80 65]
  [90 75]
  [85 68]
  [92 80]]

 [[82 88]
  [72 58]
  [94 80]
  [90 72]
  [96 85]]]

Average Scores (1D array):
 [81.6 79.8 81.7]

Attendance Data (1D array):
 [66 90 85 73 65 89 97 93 76 89]


![Alt Text](https://drive.google.com/uc?export=download&id=1uXQGh4JIGmX9Q0zoBCayh-AkR1f3lKxx)

# Exercise: Analyzing Workout Metrics with NumPy

You're embarking on a fitness journey and have started tracking your daily workout metrics using a mobile app. You've recorded the number of push-ups, sit-ups, and squats you do each day for the past week.

Task:

Data Loading:Create NumPy arrays to store the following daily workout metrics for the past week:

>1. Number of push-ups
>2. Number of sit-ups
>3. Number of squats

Data Analysis:Calculate the total number of push-ups, sit-ups, and squats performed over the past week.
Compute the average number of push-ups, sit-ups, and squats per day.
Determine the day with the highest and lowest number of push-ups, sit-ups, and squats.

Statistical Analysis: Find the median and standard deviation of each exercise to understand the central tendency and variability.
Determine the quartiles to identify the spread of data distribution.
Data Interpretation:

Reflect on your workout performance and identify areas for improvement.
Set specific goals for increasing the number of repetitions for each exercise based on the analysis.


# Sample dataset

You can use these arrays to perform various analyses and computations on the workout data. Feel free to customize the values or add more workout metrics as needed for your exercise.


In [ ]:
import numpy as np
#Create NumPy arrays for workout metrics
pushups = np.array([20, 25, 30, 15, 20, 18, 22]) # Number of push-ups each day
situps = np.array([30, 35, 40, 25, 30, 28, 32]) # Number of sit-ups each day
squats = np.array([25, 20, 30, 20, 25, 23, 28]) # Number of squats each day